name: Testing CI with Github Actions
on:
  workflow_dispatch:
    inputs:
      chosen-os:
        required: false
        type: choice
        options:
        - linux
        - ubuntu-latest
        - macOS-latest
        - windows-latest
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
        - name: Checkout from repo
          uses: actions/checkout@v3
        - name: Installing Node
          uses: actions/setup-node@v3
          with:
            node-version: 20
        - name: Install dependencies
          run: npm install
        - name: Running tests
          run: npm run test:local
        - uses: actions/upload-artifact@v1
          with:
            name: AllureReport
            path: .\allure-report